#!/bin/bash
# set -x

# Analyze ci artifacts
# ci-analysis $1 $2
# CI_DIR=myartifactdir ci-analysis sandbox

#   $2 is the (optional) dir that contains the artifacts
#      The CI_DIR environment variable may be used
#   $1 test is the test to run (default all):
#     all  - run all tests

# In general the items reported here may or may not be errors.
# The context is important. So this gives a place to dive in and
# look around. As time goes on this script will do more context
# analysis.

# TODO: possible additional tests
# cni not found up to 5 times
# ovn kube prev log with panic

help ()
{
    echo "commands:"
    echo "  panic fatal error refused notice t6443 previous badcert"
    echo "  oomkilled missingcni bearertoken healthz blockingPicker"
    echo "  sandbox lease"
}

if [[ ${1:-XX} == "help" ]] ; then
    help
    exit 0
fi


if [[ ${2:-XX} == "XX" ]] ; then
    dir=${CI_DIR:-XX}
    if [[ ${dir:-XX} == "XX" ]] ; then
        echo "Must supply directory as either CI_DIR or arg 2"
        exit 1
    fi
else
	dir=${2}
fi
echo "Analyze directory: ${dir}"

test=${1}
if [[ ${1:-XX} == "XX" ]] ; then
  test=all
fi
echo "Analyze test: ${test}"


# ----------------------------------------
# test functions

panic ()
{
	echo "===================================================="
	echo "  Looking for 'Observed a panic' in the *.log files"
	find ${dir} -name \*log | xargs grep "Observed a panic"
}

fatal ()
{
	echo "===================================================="
	echo "  Looking for 'fatal' in the *.log files"
	files=$(find ${dir} -name \*log)
	for f in ${files} 
	do
		grep "fatal" ${f} -l
	done
}

error ()
{
	echo "===================================================="
	echo "  Looking for 'error' in the *.log files"
	files=$(find ${dir} -name \*log)
	for f in ${files} 
	do
		grep -i -e "ERROR"  ${f} -l
	done
	echo "===================================================="
	echo "  Looking for '^E' in the *.log files"
	for f in ${files} 
	do
		grep -e "^E"  ${f} -l
	done
	echo "===================================================="
	echo "  Looking for ' E ' in the *.log files"
	for f in ${files} 
	do
		grep -e " E " ${f} -l
	done
}

refused ()
{
	echo "===================================================="
	echo "  Looking for 'connection refused' in the *.log files"
	files=$(find ${dir} -name \*log)
	for f in ${files} 
	do
		grep -n -e "connection refused" ${f} -l
		#grep -n -e "connection reset by peer" ${f} -l
	done
}

t6443 ()
{
	echo "===================================================="
	echo "  Looking for ':6443: connect: connection refused' in the *.log files"
	files=$(find ${dir} -name \*log)
	for f in ${files} 
	do
		grep -n -e ":6443: connect: connection refused" ${f} -l
	done
}

notice ()
{
	echo "===================================================="
	echo "  Looking for 'NOTICE' in the *.log files"
	files=$(find ${dir} -name \*log)
	for f in ${files} 
	do
		grep -e "NOTICE" ${f} -l
	done
}

previous ()
{
	echo "===================================================="
	echo "  Looking for non-zero  *previous.log files"
	files=$(find ${dir} -name \*previous.log)
	for f in ${files} 
	do
		size=$(wc -l ${f} | gawk '{ print $1 }')
		if [[ ${size} == 0 ]] ; then
			continue
		fi
		echo ${f}
	done
}

badcert ()
{
	echo "===================================================="
	echo "  Looking for 'bad certificate' in the *.log files"
	files=$(find ${dir} -name \*log)
	for f in ${files} 
	do
		grep -e "bad certificate" ${f} -l
	done
}

oomkilled ()
{
	echo "===================================================="
	echo "  Looking for 'OOMKilled' in the artifact files"
	files=$(find ${dir} -type f )
	for f in ${files} 
	do
		grep -e "OOMKilled" ${f} -l
	done
}

missingcni ()
{
	# This may not be a problem. The kubelet can try to start containers
	# before the multus daemonset is started.
	echo "===================================================="
	echo "  Looking for 'Missing CNI default network' in the artifact files"
	files=$(find ${dir} -type f )
	for f in ${files} 
	do
		grep -e "Missing CNI default network" ${f} -l
	done
}

bearertoken ()
{
	echo "===================================================="
	echo "  Looking for 'invalid bearer token' in the artifact files"
	files=$(find ${dir} -type f )
	for f in ${files} 
	do
		grep -e "invalid bearer token" ${f} -l
	done
}

healthz ()
{
	echo "===================================================="
	echo "  Looking for 'healthz check failed' in the artifact files"
	files=$(find ${dir} -type f )
	for f in ${files} 
	do
		grep -e "healthz check failed" ${f} -l
	done
}

blockingPicker ()
{
	echo "===================================================="
	echo "  Looking for 'blockingPicker' in the artifact files"
	files=$(find ${dir} -type f )
	for f in ${files} 
	do
		grep -e "blockingPicker" ${f} -l
	done
}

sandbox ()
{
	echo "===================================================="
	echo "  Looking for 'Failed to create pod sandbox' in the artifact files"
	files=$(find ${dir} -type f )
	for f in ${files} 
	do
		grep -e "Failed to create pod sandbox" ${f} -l
	done
}


lease ()
{
	# bz1796844 Worker nodes not being registered as nodes
	echo "===================================================="
	echo "  Looking for 'failed to ensure node lease exists' in the artifact files"
	files=$(find ${dir} -type f )
	for f in ${files} 
	do
		grep -e "failed to ensure node lease exists" ${f} -l
	done
}



# ----------------------------------------
# main 

case ${test} in
  "all")
     panic
     fatal
     error
     refused
     notice
     t6443
     previous
     badcert
     oomkilled
     missingcni
     bearertoken
     healthz
     blockingPicker
     sandbox
     lease
  ;;
  "panic")
     panic
  ;;
  "fatal")
     fatal
  ;;
  "error")
     error
  ;;
  "refused")
     refused
  ;;
  "t6443")
     t6443
  ;;
  "notice")
     notice
  ;;
  "previous")
     previous
  ;;
  "badcert")
     badcert
  ;;
  "oomkilled")
     oomkilled
  ;;
  "missingcni")
     missingcni
  ;;
  "bearertoken")
     bearertoken
  ;;
  "blockingPicker")
     blockingPicker
  ;;
  "healthz")
     healthz
  ;;
  "sandbox")
     sandbox
  ;;
  "lease")
     lease
  ;;
  *)
    echo "Unknown test"
  ;;
esac

exit 0
