#!/bin/bash

action="XX"
if [ X$1 != "X" ]
then
  action=$1
fi

# this playbook sets up the hosts to be part of a cluster.
if [ ${action} == "pkg" ]
then
  ansible-playbook -i hosts hostspkg.yml
  exit 0
fi

# this playbook sets up nfs on the hosts in the cluster.
if [ ${action} == "nfs" ]
then
  ansible-playbook -i hosts hostsnfs.yml
  exit 0
fi

# this playbook sets up docker on the hosts in the cluster.
if [ ${action} == "docker" ]
then
  ansible-playbook -i hosts hostsdocker.yml
  exit 0
fi

# this playbook installs the cluster
if [ ${action} == "cluster" ]
then
  ansible-playbook -i osehosts /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml -e 'ansible_python_interpreter=/usr/bin/python3'
  exit 0
fi

# this playbook uninstalls the cluster
if [ ${action} == "uninstall" ]
then
  ansible-playbook -i osehosts /usr/share/ansible/openshift-ansible/playbooks/adhoc/uninstall.yml -e 'ansible_python_interpreter=/usr/bin/python3'
  exit 0
fi

# this playbook gets the ose facts for the cluster
if [ ${action} == "facts" ]
then
  ansible-playbook -i osehosts /usr/share/ansible/openshift-ansible/playbooks/byo/openshift_facts.yml -e 'ansible_python_interpreter=/usr/bin/python3'
  exit 0
fi



echo "hosts5run pkg|nfs|docker|cluster|uninstall|facts"
exit 1

