---
# This playbook sets up the 3 hosts to be part of a cluster.
# This is a bare metal install - 1 host per node

- name: Install tasks for 3 host, 3 node, cluster
  hosts: cluster
  user: root

  # This set of tasks prepares the host to be part of the cluster
  tasks:
  - name: install pip3 ansible
    shell: pip3 install ansible

    # openshift_additional.repo is 3.10 latest
  - name: copy files/openshift_additional.repo
    copy: src=files/openshift_additional.repo dest=/etc/yum.repos.d/openshift_additional.repo

  - name: install packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present
    with_items:
      - yum
      - yum-utils
#     - python2-dbus
      - python3-dbus
      - firewalld
      - NetworkManager
      - docker
      - iptables-services
      - vim
      - emacs-nox
      - gcc
      - gdb
      - crash
      - net-tools
      - tcpdump
      - nfs-utils
      - nfs4-acl-tools
      - libnfsidmap
      - wget
      - git
      - bind-utils
      - bridge-utils
      - bash-completion
      - atomic-openshift-excluder
      - atomic-openshift-docker-excluder
      - openshift-ansible
      - openshift-ansible-docs
      - openshift-ansible-playbooks
      - openshift-ansible-roles

# - name: update packages
#   shell: dnf -y update

